model:
    type: SingleStageFramework
    preprocessor:
        type: Preprocessor
        mean: [123.675, 116.28, 103.53]
        std: [58.395, 57.12, 57.375]
        bgr_to_rgb: true
        pad_size_divisor: 32
    backbone:
        type: ResNet
        depth: 50
        frozen_stages: 1
        norm_eval: true
        return_stages: ['layer1', 'layer2', 'layer3', 'layer4']
        pretrained: 'jittorhub://resnet50.pkl'
    neck:
        type: FPN
        in_channels: [256, 512, 1024, 2048]
        out_channels: 256
        start_level: 1
        add_extra_convs: on_input
        num_outs: 5
    bbox_head:
        type: GFLHead
        num_classes: 80
        in_channels: 256
        stacked_convs: 4
        feat_channels: 256
        anchor_generator:
            type: AnchorGenerator
            ratios: [1.0]
            octave_base_scale: 8
            scales_per_octave: 1
            strides: [8, 16, 32, 64, 128]
        loss_cls:
            type: QualityFocalLoss
            use_sigmoid: true
            beta: 2.0
            loss_weight: 1.0
        loss_dfl:
            type: DistributionFocalLoss
            loss_weight: 0.25
        reg_max: 16
        loss_bbox:
            type: GIoULoss
            loss_weight: 2.0
    train_cfg:
        assigner:
            type: ATSSAssigner
            topk: 9
        allowed_border: -1
        pos_weight: -1
        debug: false
    test_cfg:
        nms_pre: 1000
        min_bbox_size: 0
        score_thr: 0.05
        nms:
            type: nms
            iou_threshold: 0.6
        max_per_img: 100
